# -*- mmm-classes: mason -*-
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<!-- BEGIN generated by mason file: (>>>FILE<<<) DO NOT EDIT THIS HTML DIRECTLY -->
  <head>
    <title>(>>>PN_MASON_TITLE<<<)</title>
    <meta name="author" content="(>>>USER_NAME<<<)">
  </head>

  <body>
    <h1>(>>>PN_MASON_TITLE<<<)</h1>

    (>>>POINT<<<)
    
    <hr>
    <address>
      <a href="mailto:(>>>EMAIL_DOT_EMACS<<<)">(>>>USER_NAME<<<)</a>,
      (>>>DATE<<<)
    </address>
  </body>
<!-- END generated by mason file: (>>>FILE<<<) DO NOT EDIT THIS HTML DIRECTLY -->
</html>
>>>TEMPLATE-DEFINITION-SECTION<<<
